[project]
name = 'corporate-risk-management'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.risk-identifier]
path = 'contracts/risk-identifier.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
